### ISSUE TITLE
Feedback - Separate Octet Option

### ISSUE THREAD

**Issue by bnski** [Nuagic/streamdeck-myip#2]
Would you consider an option that allows you to select an individual octet to display.  This would be great for readability.  

<img width="332" alt="CleanShot 2021-10-25 at 09 19 08@2x" src="https://user-images.githubusercontent.com/1579863/138702853-23988c2f-4172-40e3-aae4-15ca7b8074cd.png">

**Comment by feraudet** [comment]
Hello,
Sure, good idea !

**Comment by feraudet** [comment]
Done on bbd73f77fdebb26f036dee87f40fd6131b2db0fd
Elgato would release a new plugin version soon
