### ISSUE TITLE
about websocket.

### ISSUE THREAD

**Issue by Alvazz** [Nuagic/streamdeck-myip#5]
Hi,

I have a doubt about the "websocket = new WebSocket("ws://127.0.0.1:" + inPort);" part.

Where is the inPort parameter obtained here?
Then, does the myip plugin connect to StreamDeck as a websocket client? If so, StreamDeck is a websocket server?

**Comment by feraudet** [comment]
Hello,

As far as I know inPort is passed by StreamDeck who execute plugins code in a kind chromium virtual machine. Yes, Javascript plugins connect StreamDeck server through a websocket on a non fixed port depending on which port is available on localhost at StreamDeck start

**Comment by Alvazz** [comment]
Thanks!
